name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'     
        required: true
      note:
        description: 'Release note'
        
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm i -g @vercel/ncc
          npm i @actions/github
          npm run build
      - name: Commit changes if any
        run: |
          git config --global user.name 'wslyshptyc'
          git config --global user.email 'wesleysahputra3035@gmail.com'
          
          # Check for changes
          if [[ -n $(git status --porcelain) ]]; then
            git add package-lock.json
            git commit -am "dist build"
            git push
          else
            echo "No changes to commit."
          fi

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest
        run: |
          git config --global user.name 'wslyshptyc'
          git config --global user.email 'wesleysahputra3035@gmail.com'
          git pull
      - name: Tag it
        run: |
          git tag -a "${{ inputs.tag }}" -m "${{ inputs.note }}" master
          git push --tags
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ inputs.tag }}"
          release_name: "Release ${{ inputs.tag }}"
          body: "${{ inputs.note }}"
          draft: false
          prerelease: false
